// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwAv_Pcs66L_NMObpdIOk6z81PFyci5zg',
    appId: '1:779734123542:web:1e24c453a2c1ff6425a137',
    messagingSenderId: '779734123542',
    projectId: 'hair-haven-2faf4',
    authDomain: 'hair-haven-2faf4.firebaseapp.com',
    storageBucket: 'hair-haven-2faf4.appspot.com',
    measurementId: 'G-P9NN4WPKST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_nmilk31fxe08v3PUqs6SSB8nwAFRLug',
    appId: '1:779734123542:android:5c1098d2d3f8f47f25a137',
    messagingSenderId: '779734123542',
    projectId: 'hair-haven-2faf4',
    storageBucket: 'hair-haven-2faf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMpcXSbwmHjQWHkUjnSpcxs3bVhRSjVs8',
    appId: '1:779734123542:ios:c7c0389aea68ce5b25a137',
    messagingSenderId: '779734123542',
    projectId: 'hair-haven-2faf4',
    storageBucket: 'hair-haven-2faf4.appspot.com',
    androidClientId: '779734123542-mq0no1mm1g6ffje9t0rmjv2gr83rfmt0.apps.googleusercontent.com',
    iosClientId: '779734123542-d1kb6vgrd7enm4henuo983obd7hmf29g.apps.googleusercontent.com',
    iosBundleId: 'com.example.hairHaven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMpcXSbwmHjQWHkUjnSpcxs3bVhRSjVs8',
    appId: '1:779734123542:ios:c7c0389aea68ce5b25a137',
    messagingSenderId: '779734123542',
    projectId: 'hair-haven-2faf4',
    storageBucket: 'hair-haven-2faf4.appspot.com',
    androidClientId: '779734123542-mq0no1mm1g6ffje9t0rmjv2gr83rfmt0.apps.googleusercontent.com',
    iosClientId: '779734123542-d1kb6vgrd7enm4henuo983obd7hmf29g.apps.googleusercontent.com',
    iosBundleId: 'com.example.hairHaven',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwAv_Pcs66L_NMObpdIOk6z81PFyci5zg',
    appId: '1:779734123542:web:d0ab5547bb89a26025a137',
    messagingSenderId: '779734123542',
    projectId: 'hair-haven-2faf4',
    authDomain: 'hair-haven-2faf4.firebaseapp.com',
    storageBucket: 'hair-haven-2faf4.appspot.com',
    measurementId: 'G-TWY65J1ZPW',
  );

}